# Generated by Django 5.0.3 on 2024-03-29 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otpmodel_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 3, 29, 4, 26, 34, 731790), editable=False, null=True),
        ),
    ]
