# Generated by Django 5.0.3 on 2024-03-29 07:30

import datetime
import django.contrib.auth.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otpmodel_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 3, 29, 7, 35, 32, 728243), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
