# Generated by Django 5.0.3 on 2024-03-29 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otpmodel_expires_at_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 3, 29, 7, 47, 48, 935622), editable=False, null=True),
        ),
    ]
