# Generated by Django 5.0.3 on 2024-03-31 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_otpmodel_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 3, 31, 13, 7, 17, 641332), editable=False, null=True),
        ),
    ]
