# Generated by Django 5.0.3 on 2024-04-05 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_otpmodel_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 4, 5, 13, 12, 22, 584157), editable=False, null=True),
        ),
    ]
